---
title: "Étude de l'insuffisance rénale chronique (IRC)"
author: "___"
date: "___"
output: html_document
---

```{r setup}
SciViews::R
```

<!--% Utilisez le code suivant pour importer les données dans la variable `irc`. -->

<!--# Note: les patients du jeu de données initial pour lesquels il y avait des données manquantes dans les variables nominales ont été supprimés. -->

```{r importation}
irc <- read("../data/irc.rds")
names(irc)
```

<!--# La signification des variables et les unités sont expliquée ici: https://archive.ics.uci.edu/ml/datasets/Chronic_Kidney_Disease (le nom des variables est conservé, mais les niveaux, les labels et les unités sont francisés) -->

<!--% Réalisez un dénombrement par classe (`class`) des patients présentant ou non une coronaropathie (`cad`) en utilisant des aplats (surfaces) colorés par défaut. Interprétez votre graphique en texte Markdown juste en dessous en maximum 5 phrases. -->

```{r bar1}

```

<!--% Réalisez un dénombrement par classe (`class`) des patients présentant ou non des amas de pyocytes (`pcc`) = "cellules de pus" en utilisant des aplats de couleurs de type 'viridis'. Utilisez l'argument `position = "dodge"` Interprétez votre graphique en texte Markdown juste en dessous en maximum 5 phrases. -->

```{r bar2}

```

```{=html}
<!--% Réalisez deux graphiques du dénombrement de l’hypertension (`htn`) en distinguant par la couleur les patients présentant un diabète sucré (`dm`). Utilisez un graphique en facettes pour la classe de patients (`class`). Pour le premier graphique, utiliser l'argument `position = "stack"` (option par défaut). Pour le second graphique, utiliser l'argument `position = "fill"`.
Interprétez votre premier graphique en texte Markdown juste en dessous de lui en maximum 5 phrases. En dessous du second graphique, et toujours sous forme de texte Markdown, comparez les deux graphiques au niveau de l'axe des ordonnées ? Dites lequel vous parait le plus adéquat ici et pourquoi. -->
```
```{r bar3a}
# Avec position = "stack"

```

```{r bar3b}
# Avec position = "fill"

```

<!--% Réalisez un graphique en barres de la moyenne de la concentration en urée sanguine (`bu`) en fonction de la classe (`class`). Interprétez votre graphique en texte Markdown juste en dessous en maximum 5 phrases. -->

```{r bar4}

```

<!--% Réalisez des boites de dispersion de la glycémie (`bgr`) en fonction de la classe (`class`). Interprétez votre graphique en texte Markdown juste en dessous en maximum 5 phrases. -->

```{r boxplot1}

```

<!--% Réalisez des boites de dispersion de la concentration en sodium (`sod`) en fonction de la classe (`class`) (axe X) et de l'hypertension (`htn`) sous forme d'aplats de couleurs 'viridis'. Indiquez le nombre d'observation sur votre graphique au dessus des boites de dispersion. Interprétez-le (texte Markdown juste en dessous) en maximum 5 phrases. -->

```{r boxplot2}
give_n <- function(x)
  c(y = max(x) * 1.1, label = length(x)) 

```

<!--% Réalisez deux graphiques en boites de dispersion parallèles, l'un représentant le nombre de globules blancs (`wc`) et l'autre le nombre de globules rouges (`rc`) en fonction de la classe (`class`). Ajoutez de la couleur (palette par défaut) en fonction de la classe. Assemblez ces deux graphiques sur une seule figure avec légende unique pour les deux et interprétez-les complètement en maximum 5 phrases (texte Markdown juste en dessous). -->

```{r boxplot3composite}

```

<!--% Réalisez et commentez deux graphiques originaux (un graphique en barre et une boite de dispersion) à partir du jeu de données `irc`. Les graphiques doivent être pertinents et vous les interpréterez et justifierez vos choix en texte Markdown juste en dessous de chacun d'entre eux. -->

```{r perso1}

```

```{r perso2}

```

<!--# Lorsque vous aurez terminé, assurez-vous que le document compile (bouton 'Knit') sans erreurs et que vous avez conservé la structure initiale du document, en particulier les labels des chunks. -->

